import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { Language, Parser, Query } from 'web-tree-sitter';
import { buildTokenSpans, type RawCapture, type TokenSpan } from './tokenize';

export interface GrammarPaths {
  /** Directory holding the emscripten runtime wasm (web-tree-sitter.wasm). */
  readonly runtimeDir: string;
  /** The Tono parser compiled to wasm from the pinned grammar revision. */
  readonly parserWasmPath: string;
  /** The grammar's own queries/highlights.scm, copied verbatim at build time. */
  readonly queryPath: string;
}

let runtimeReady: Promise<void> | undefined;

// Parser.init boots a shared emscripten module, so it must happen exactly once
// per extension host even if the highlighter is reloaded. A rejection is not
// cached: otherwise one transient failure to read the runtime wasm would disable
// highlighting for the whole session, and the retry the user reaches for
// (toggling tono.highlight.enabled) would keep replaying the stale error.
function initRuntime(runtimeDir: string): Promise<void> {
  runtimeReady ??= Parser.init({
    locateFile: (name: string) => path.join(runtimeDir, name),
  }).catch((error: unknown) => {
    runtimeReady = undefined;
    throw error;
  });
  return runtimeReady;
}

export class TonoHighlighter {
  private constructor(
    private readonly parser: Parser,
    private readonly query: Query
  ) {}

  static async load(paths: GrammarPaths): Promise<TonoHighlighter> {
    await initRuntime(paths.runtimeDir);

    const [parserWasm, querySource] = await Promise.all([
      readFile(paths.parserWasmPath),
      readFile(paths.queryPath, 'utf8'),
    ]);

    const language = await Language.load(parserWasm);

    // setLanguage throws when the grammar was generated by an incompatible
    // tree-sitter CLI, and a Query throws when it does not match the grammar.
    // Both leave wasm allocations behind unless the parser is freed here.
    let parser: Parser | undefined;
    try {
      parser = new Parser();
      parser.setLanguage(language);
      return new TonoHighlighter(parser, new Query(language, querySource));
    } catch (error) {
      parser?.delete();
      throw new Error(
        `the compiled grammar and ${path.basename(paths.queryPath)} could not be loaded together: ${String(error)}`
      );
    }
  }

  highlight(text: string): TokenSpan[] {
    const tree = this.parser.parse(text);
    if (!tree) {
      return [];
    }
    try {
      const captures: RawCapture[] = this.query.captures(tree.rootNode).map((capture) => ({
        name: capture.name,
        patternIndex: capture.patternIndex,
        startIndex: capture.node.startIndex,
        endIndex: capture.node.endIndex,
      }));
      return buildTokenSpans(text, captures);
    } finally {
      // Trees live in wasm memory that the JS garbage collector cannot reclaim.
      tree.delete();
    }
  }

  dispose(): void {
    this.query.delete();
    this.parser.delete();
  }
}
